[package]
name = "wlr-which-key"
version = "1.3.0"
edition = "2024"
description = "Keymap manager for wlroots-based compositors"
repository = "https://github.com/MaxVerevkin/wlr-which-key/"
readme = "README.md"
license = "GPL-3.0-only"
authors = ["MaxVerevkin <maxxverr@gmail.com>"]

[dependencies]
pangocairo = "0.21.5"
anyhow = "1.0.101"
libc = "0.2.181"
serde = { version = "1.0.228", features = ["derive"] }
wayrs-client = "1.3.1"
wayrs-protocols = { version = "0.14.11", features = [
    "wlr-layer-shell-unstable-v1",
    "keyboard-shortcuts-inhibit-unstable-v1",
] }
wayrs-utils = { version = "0.17.2", features = [
    "shm_alloc",
    "seats",
    "keyboard",
] }
smart-default = "0.7.1"
clap = { version = "4.5.58", default-features = false, features = [
    "std",
    "derive",
    "help",
    "usage",
] }
toml = "1.0.1"
dirs = "6.0.0"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
